# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snapseed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snapseed
  pod 'SnapKit'

  target 'SnapseedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnapseedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
